rhythm:
	clang++ -std=c++17 -Iinclude src/*.cpp src/*.mm -I/opt/homebrew/include -L/opt/homebrew/lib -laubio -lraylib -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -framework AppKit -o rhythm

clean:
	rm -f rhythm
