chess:
	g++ -std=c++17 src/main.cpp src/model/ChessModel.cpp src/view/ChessView.cpp src/controller/ChessController.cpp -Iinclude -I/opt/homebrew/include -L/opt/homebrew/lib  -lraylib -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -o chess
